# Site settings
title: Ray's Blog
tagline: ''
sidebar_image: /images/cover.jpg
lang: 'zh-cmn-Hans'
url: http://www.predatorray.me
author: Wenhao Ji
plus: https://plus.google.com/u/0/109983541653192037061/posts

# Build settings
markdown: kramdown
highlighter: pygments
baseurl: # the subpath of your site, e.g. /blog/

permalink:   /:categories/:title/
